using System;
using System.Collections.Generic;
using System.IO;
using Ketchapp.Editor.Utils;
using Ketchapp.MayoSDK.Purchasing;
using UnityEditor;
using UnityEngine;
namespace Ketchapp.Editor.Purchasing
{
    public static class IAPEditor
    {
        public static string PurchasingEnumPath => Path.Combine(Application.dataPath, "Dependencies", "Ketchapp", "Configuration", "PurchasingObjects.cs");

        // TODO : This whill be used for Mayo 1.2.2.2 until a majority of dev have updated
        private static string OldPurchasingEnumPath => Path.Combine(Application.dataPath, "Ketchapp", "Public", "Purchasing", "PurchasingObjects.cs");

        public static void CreatePurchasingEnum(List<ProductDescription> products)
        {
            if (File.Exists(OldPurchasingEnumPath))
            {
                File.Delete(OldPurchasingEnumPath);
            }

            using (StreamWriter sw = new StreamWriter(PurchasingEnumPath))
            {
                sw.WriteLine("// Auto-generated by Ketchapp Mayo SDK\n");
                sw.WriteLine("public enum PurchasingObjects");
                sw.WriteLine("{");
                sw.WriteLine($"\tNone,");
                foreach (var product in products)
                {
                    sw.WriteLine($"\t{product.ProductName},");
                }

                sw.WriteLine("}");
            }

            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("IAP Generator", "IAP Configuration has been generated !", "Ok !");
        }

        public static void GenerateDefaultPurchasingFile()
        {
            if (File.Exists(OldPurchasingEnumPath))
            {
                var config = Resources.Load<IAPConfiguration>("IAPConfiguration");
                if (config != null)
                {
                    CreatePurchasingEnum(config.Products);
                }
            }
            else
            {
                using (StreamWriter sw = new StreamWriter(PurchasingEnumPath))
                {
                    sw.WriteLine("// Auto-generated by Ketchapp Mayo SDK\n");
                    sw.WriteLine("public enum PurchasingObjects");
                    sw.WriteLine("{");
                    sw.WriteLine($"\tNone,");
                    sw.WriteLine("}");
                }

                AssetDatabase.Refresh();
            }
        }
    }
}
